services:
  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginxproxymanager_data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  uptimekuma:
    image: louislam/uptime-kuma:1
    container_name: uptimekuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma_data:/app/data

volumes:
  nginxproxymanager_data:
  uptimekuma_data:
